server:
  servlet:
    context-path: /api

spring:
  application:
    name: score-api
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

logging:
  pattern:
    level: "[TraceId: %X{traceId}, SpanId: %X{spanId}]"